version: '3.4'

services:
  yourchores.server:
    image: ${DOCKER_REGISTRY-}no1225/yourchoresserver
    environment:
      MYSQL_SERVICE_HOST: "db"
      MYSQL_SERVICE_PORT: "3306"
      MYSQL_DATABASE: "YourChoresDb"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbuserpassword"
    build:
      context: .
      dockerfile: YourChores.Server/Dockerfile
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: "YourChoresDb"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbuserpassword"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
  nginx:
    image: linuxserver/letsencrypt
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=api.yourchores.me
      - VALIDATION=http
      - STAGING=false #optional
    volumes:
      - ./nginx/config:/config
      - ./nginx/nginx.conf:/config/nginx/site-confs/default
      - ./nginx/ssl.conf:/config/nginx/ssl.conf
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
volumes:
  dbdata: