version: '3.4'

services:
  yourchores.server:
    image: ${DOCKER_REGISTRY-}no1225/yourchoresserver
    environment:
      MYSQL_SERVICE_HOST: "db"
      MYSQL_SERVICE_PORT: "3306"
      MYSQL_DATABASE: "YourChoresDb"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbuserpassword"
    build:
      context: .
      dockerfile: YourChores.Server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: "YourChoresDb"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbuserpassword"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
volumes:
  dbdata: